### PR TITLE
v1.12.0 release

### PR DESCRIPTION
**Pull request by nurikk**
Build image for latest release

### CODE REVIEW

**Review by nilsnolde — APPROVED** [review]
great thanks. think you got it all, seems to come without an update to vroom-express.

**Review by jcoupey — COMMENTED** [review]
Not much added on the `vroom-express` side but I still drafted a `v0.11.0` release so that the latest additions can be included here.

**Comment by nurikk** [comment]
> Not much added on the `vroom-express` side but I still drafted a `v0.11.0` release so that the latest additions can be included here.

Bumped vroom-express version as well

**Comment by nilsnolde** [comment]
Thanks @nurikk ! One thing I also always forget: can you add a section to the changelog?

**Pull request merged**
