### PR TITLE
first try for multi-stage build

### LINKED ISSUE #3: Decrease final image size
The current (decompressed) image size is 1.16 GB. That really brings down the joy when pulling from Dockerhub.

Proposed solution:

Multi-stage build similar to OSRM: https://hub.docker.com/r/osrm/osrm-backend/dockerfile. That has only a decompressed size of 100 MB.

### PR DESCRIPTION
**Pull request by nilsnolde**
Fixes #3 

Does now a multi-stage build for the final image:
1. build stage: installs all dependencies to build vroom and clones both repos
2. run stage: only installs needed linked libs, copies vroom binary and vroom-express repo from build stage, and installs (and runs) the node project

However, even now the final image size is close to 1 GB. The `libboost-all-dev` libs are HUGE! If I leave that out of the image, the final size is only 215 MB, even with `libssl-dev`!

So, I'm wondering @jcoupey, can we do it similar to `osrm` and only install the boost components vroom needs to run? They do this in their [Dockerfile](https://hub.docker.com/r/osrm/osrm-backend/dockerfile):

```
apt-get install -y --no-install-recommends libboost-program-options1.62.0 libboost-regex1.62.0 \
        libboost-date-time1.62.0 libboost-chrono1.62.0 libboost-filesystem1.62.0 \
        libboost-iostreams1.62.0 libboost-thread1.62.0 expat liblua5.2-0 libtbb2 &&\
```

Or would that entail a change in the `makefile`? I'm hopeless with C++ builds..

### CODE REVIEW

**Comment by jcoupey** [comment]
We use two components from boost: `asio` and `optional`. They're typically included with:

```
#include <boost/asio.hpp>
#include <boost/optional.hpp>
```

My understanding is that those are header-only libraries required at the build stage so you actually don't need any boost-related package at the run stage.

I think that if it weren't for the `boost::optional` stuff, we would only have to install [libasio-dev](https://packages.debian.org/buster/libasio-dev) at the build stage. Would this change the need for a multi-stage build?

**Comment by nilsnolde** [comment]
I tried using it without the boost dependency in the running stage, but then requests fail with a `Internal error` vroom error. 

I tried to only include `libboost-iostreams1.67.0` of the boost suite (earlier versions, e.g. 1.62.0, don't seem to be distributed for `debian:buster`), but again the same error. Maybe it doesn't include the `optional` stuff or `1.67.0` is not compatible with `vroom`?!

I saw the `vroom` [#312](https://github.com/VROOM-Project/vroom/issues/312) you put in. That would be really cool if boost wouldn't be a dependency at all anymore. Not only for Docker. 

Then I won't do any more on this and we can fix once vroom was updated. Ok for you?

**Comment by jcoupey** [comment]
> That would be really cool if boost wouldn't be a dependency at all anymore

This won't happen totally because there is still the need for `boost::asio` (but then installing `libasio-dev` should be enough for the build stage).

I'm puzzled and not sure the problem comes from either `boost::asio` or `boost::optional` because:

- `asio` is header-only (see [installed files](https://packages.debian.org/buster/all/libasio-dev/filelist))
- if think there is no system library required for the `boost::optional` part (though there don't seem to be a simple way to install only the `boost/optional` headers without pulling the whole `libboost-dev` stuff).

We may need a bit of digging here, can you spot the error logged by `vroom-express` for the `Internal error` you mention?

**Comment by krypt-n** [comment]
`asio` is not exactly header only, since it requires `libboost-system` (https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/using.html). So installing
```
        libboost-system1.67.0
        libssl1.1
```
should be enough, if vroom is compiled without libosrm support.

**Comment by jcoupey** [comment]
@krypt-n thanks for stepping in!

>at least vroom is compiled so that it requires it

You mean we could avoid it?

> if vroom is compiled without linking against libosrm.

I don't think we should worry about this (at least for now) in the context of a simple Docker image.

**Comment by krypt-n** [comment]
Ah sorry, I was mistaken. It seems like `boost::system` is a hard requirement for `asio` and thus `libboost-system` needs to be present at runtime. However, this just adds a at most few MB to the docker image, so I think it can be ignored

**Comment by nilsnolde** [comment]
Oh great, thanks so much for the insight @krypt-n ! I'll amend that next week!

> I don't think we should worry about this (at least for now) in the context of a simple Docker image
Ýeah I agree. In the future, maybe we can extend the Dockerfile to optionally build `libosrm` with a build argument, so an additional routing container wouldn't be needed.

**Comment by nilsnolde** [comment]
Yep, that worked @krypt-n, thanks again:) Image size now down to 209MB uncompressed, great!

**Pull request merged**
